name: CrackedBlocks
main: lee.code.crackedblocks.CrackedBlocks
version: ${project.version}
api-version: 1.18
author: Lee
commands:
  crackedblocks:
    description: Main command for plugin.
    permission: cb.command.use
    aliases: cb